FROM python:3.8-slim

# # Создать директорию вашего приложения.
# RUN mkdir /app
# Сделать директорию /app рабочей директорией. 
WORKDIR /app

# Скопировать с локального компьютера файл зависимостей
# в директорию /app.
# COPY requirements.txt /app
COPY requirements.txt .


# Выполнить установку зависимостей внутри контейнера.
# RUN pip3 install -r /app/requirements.txt --no-cache-dir
RUN pip3 install -r requirements.txt --no-cache-dir

# Скопировать содержимое директории /api_yamdb c локального компьютера
# в директорию /app.
# COPY ./ /app = COPY .. /app
# COPY ./ /app
COPY ./ .

# # Сделать директорию /app рабочей директорией. 
# WORKDIR /app

# Выполнить запуск сервера разработки при старте контейнера.
CMD ["gunicorn", "api_yamdb.wsgi:application", "--bind", "0:8000" ] 